export const Fonts = {
    ARIMA: require('../../assets/fonts/ArimaMadurai-Black.ttf'),
    ARIMA_BOLD: require('../../assets/fonts/ArimaMadurai-Bold.ttf'),
    ARIMA_EXBOLD: require('../../assets/fonts/ArimaMadurai-ExtraBold.ttf'),
    ARIMA_EXLIGHT: require('../../assets/fonts/ArimaMadurai-ExtraLight.ttf'),
    ARIMA_LIGHT: require('../../assets/fonts/ArimaMadurai-Light.ttf'),
    ARIMA_MEDIUM: require('../../assets/fonts/ArimaMadurai-Medium.ttf'),
    ARIMA_REGULAR: require('../../assets/fonts/ArimaMadurai-Regular.ttf'),
    ARIMA_THIN: require('../../assets/fonts/ArimaMadurai-Thin.ttf'),
    COURGETTE: require('../../assets/fonts/Courgette-Regular.ttf'),
    FUGAZONE: require('../../assets/fonts/FugazOne-Regular.ttf'),
    NUNITO: require('../../assets/fonts/Nunito-Black.ttf'),
    NUNITO_ITALIC: require('../../assets/fonts/Nunito-BlackItalic.ttf'),
    NUNITO_BOLD: require('../../assets/fonts/Nunito-Bold.ttf'),
    NUNITO_BOLD_ITALIC: require('../../assets/fonts/Nunito-BoldItalic.ttf'),
    NUNITO_EXBOLD: require('../../assets/fonts/Nunito-ExtraBold.ttf'),
    NUNITO_EXBOLD_ITALIC: require('../../assets/fonts/Nunito-ExtraBoldItalic.ttf'),
    NUNITO_EXLIGHT: require('../../assets/fonts/Nunito-ExtraLight.ttf'),
    NUNITO_EXLIGHT_ITALIC: require('../../assets/fonts/Nunito-ExtraLightItalic.ttf'),
    NUNITO_LIGHT: require('../../assets/fonts/Nunito-Light.ttf'),
    NUNITO_LIGHT_ITALIC: require('../../assets/fonts/Nunito-LightItalic.ttf'),
    NUNITO_REGULAR: require('../../assets/fonts/Nunito-Regular.ttf'),
    NUNITO_SEMI_BOLD: require('../../assets/fonts/Nunito-SemiBold.ttf'),
    NUNITO_SEMI_BOLD_ITALIC: require('../../assets/fonts/Nunito-SemiBoldItalic.ttf'),
    STAATLICHES: require('../../assets/fonts/Staatliches-Regular.ttf')
}